title: My blog

email: platina.kusakina@gmail.com

description: 설명 넣는곳

baseurl: ""

url: "kusakina0608@github.io"

timezone: Asia/Seoul

repository: kusakina0608/kusakina0608.github.io

github_username: kusakina0608

permalink: /:year/:month/:day/:title/ # url을 어떻게 구성할 것인지

excerpt_separator: <!--more--> # post에서 추출할 때 무엇을 기준으로 추출할 것인지 주로 미리보기에 사용된다.

markdown: kramdown # markdown 설정

kramdown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate # 페이지 네이션 설정

paginate: 5 # 몇 개의 포스트를 1개 페이지에 표시할 것인지
paginate_path: '/page/:num/' # 페이지네이션 경로

exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock, vendor] # Jekyll이 무시할 목록

keep_files: [assets, files] # 유지할 파일들

author: username # author
asset_url: /assets # assets의 경로
image: '' # 블로그 기본 이미지


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed